README.md, requirements.txt, setup.py, tap_sftp/aws_secrets_manager.py, tap_sftp/client.py, tap_sftp/decrypt.py, tap_sftp/helper.py, tap_sftp/singer_encodings/json_schema.py, tap_sftp/sync.py, tap_sftp/tap.py
https://varicent.atlassian.net/browse/WP-11182
Added AWS Secret Manager as key storage
Use temp director as gpg home directory if not provided
=> WP-11182 Enable pgp encryption in tap sftp

setup.py, tap_sftp/client.py
WP-11718 Import gets stuck when user tries to refresh data after credentials change to something invalid
https://varicent.atlassian.net/browse/WP-11718
notes:
- reduced connection retry attempts and removed backoff rate
=> WP-11718 Import gets stuck when user tries to refresh data after credentials change to something invalid

pyproject.toml, tap_sftp/tap.py
Enable Column Type Change for SFTP Import Connector
https://varicent.atlassian.net/browse/WP-11950
notes: minor bug fix on columns_to_update config to check whether columnUpdateType is modify
=> WP-11950 Enable Column Type Change for SFTP Import Connector

poetry.lock, pyproject.toml
Excel Import does not recognize date type columns formatted as mm/dd/yyyy
https://varicent.atlassian.net/browse/WP-11762
=> WP-11762 Excel Import does not recognize date type columns formatted as mm/dd/yyyy

poetry.lock, pyproject.toml
WP-12538 Excel Import fails when column name is longer than 150 characters
https://varicent.atlassian.net/browse/WP-12538
=> WP-12538 Excel Import fails when column name is longer than 150 characters

poetry.lock, pyproject.toml
=> WP-12560 raise error on excel invalid specification

pyproject.toml, tap_sftp/client.py
- can occur during refresh if file previously imported is already deleted from sftp server
=> WP-13046 throw error when no files are found during sync/discovery

pyproject.toml, tap_sftp/sync.py
Task: https://varicent.atlassian.net/browse/WP-14058
=> WP-14058 SFTP Import issue with file name containing parentheses

.github/workflows/tests.yml, poetry.lock, pyproject.toml
WP-14093 Import file with duplicate headers is failing
https://varicent.atlassian.net/browse/WP-14093
notes:
- version update for file_processors change
=> WP-14093 Import file with duplicate headers is failing

poetry.lock, pyproject.toml
https://varicent.atlassian.net/browse/WP-13911
Changes all in file-processors - will update to correct version before merge.
=> WP-13911: Add support for inferring date, boolean for csv imports

poetry.lock, pyproject.toml, tap_sftp/sync.py, tap_sftp/tap.py, tests/sftp_tests/test_sync.py
https://varicent.atlassian.net/browse/WP-14512
- remove old function to fix schema in catalog as file-processors don't use it
=> WP-14512 use columns_to_update for tap

poetry.lock, pyproject.toml
https://varicent.atlassian.net/browse/WP-14173
=> WP-14173 update file-processors version

poetry.lock, pyproject.toml
https://github.com/symon-ai/file-processors/pull/39
- bump file processors version for ^
=> WP-15016 fix date columns not getting right data type during discovery

poetry.lock, pyproject.toml, tap_sftp/discover.py, tap_sftp/sync.py
WP-14838 data pre-process configuration: header/footer rows and column header [API]
https://varicent.atlassian.net/browse/WP-14838
notes:
- need to update poetry.lock after fp pr gets merged.
=> WP-14838 data pre-process configuration: header/footer rows and column header [API]

poetry.lock, pyproject.toml
JIRA: https://varicent.atlassian.net/browse/WP-15399
We may run into cases that user updates one column from DayCalls to New DayCalls, then append a new column called DayCalls. Using a dict to hold the values would cause the new column missing. Use the list instead of the dict here.
JIRA: https://varicent.atlassian.net/browse/WP-15397
The dtype for the error columns are detected as bool and float64, update the infer_column for them.
=> WP-15397 update file-processors version, fwf failed with bool and float64

poetry.lock, pyproject.toml, tap_sftp/client.py, tap_sftp/discover.py, tap_sftp/sync.py, tap_sftp/tap.py, tests/sftp_tests/test_client.py
WP-15934 [Import] Improve error handling for SFTP, GSheets, Excel, FWF,OneDrive
https://varicent.atlassian.net/browse/WP-15934
TODO:
update pyproject.toml, poetry.lock after file-processor release created
=> WP-15934 [Import] Improve error handling for SFTP, GSheets, Excel, FWF,OneDrive

poetry.lock, pyproject.toml
update version for fp change in this pr: https://github.com/symon-ai/file-processors/pull/51
=> WP-15934 [Import] Improve error handling for SFTP, GSheets, Excel, FWF,OneDrive - bug fix 

poetry.lock, pyproject.toml
- bump file processors and urllib3 version
=> WP-17423 add source type to csv import

pyproject.toml, tap_sftp/tap.py
WP-17438 Error handling clean up
https://varicent.atlassian.net/browse/WP-17438
=> WP-17438 Error handling clean up

pyproject.toml, tap_sftp/client.py
https://varicent.atlassian.net/browse/WP-17646
=> WP-17646 change error message wording to include server availability

poetry.lock, pyproject.toml
WP-16421 Imports isn't recognizing booleans
https://varicent.atlassian.net/browse/WP-16421
notes: version update for fp pr https://github.com/symon-ai/file-processors/pull/55
=> WP-16421 Imports isn't recognizing booleans

tap_sftp/client.py
SF#00244407 - Ceratizit - Not able to correctly import file from sftp
https://varicent.atlassian.net/browse/WP-18182
notes: 
- client had another file with filename matching the search pattern. fix to indicate the start in the regex
- version update to be done in https://github.com/symon-ai/tap-sftp/pull/43
=> WP-18121 SF#00244407 - Ceratizit - Not able to correctly import file from sftp

pyproject.toml, tap_sftp/discover.py, tap_sftp/helper.py, tap_sftp/sync.py, tests/sftp_tests/test_discover.py
Task: https://varicent.atlassian.net/browse/WP-19501
Main app pr: https://github.com/symon-ai/app/pull/13796
Changes:
- file size validation is skipped for csv/txt files when enable_import_file_copy feature flag is on
=> WP-19501 SFTP CSV Import - Scalability & Performance

pyproject.toml, tap_sftp/sync.py
* add log lines for debugging
* matches_key change for dynamic for tablename starting with *
* fix issue in table name match
* fix logging error
* increase version, cleanups
=> WP-26817 handle dynamic large import starting with wildcard (#61)
